version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.2
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181

  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:6.2.2
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 9092:9092

  schema-registry:
    depends_on:
      - kafka
      - zookeeper
    image: confluentinc/cp-schema-registry:6.2.2
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
    ports:
      - 8081:8081

  kafka-clients:
    build:
      context: .
      args:
        - pip_extra_index_url=${PIP_EXTRA_INDEX_URL}
    command: demos.kafka.clients
    depends_on:
      - kafka
      - schema-registry

  kinesis-consumer:
    build:
      context: .
      args:
        - pip_extra_index_url=${PIP_EXTRA_INDEX_URL}
    command: demos.kinesis.consumer
    environment:
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - KINESIS_STREAM
      - KINESIS_STREAM_GZIPPED
